# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5P0FnvzhooIVB-8QWy0ziQ2AaefCD2S
"""

# --- CELL 1: Setup ---
import os
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate

# Set GROQ_API_KEY in your shell or .env file before running the app.
# --- CELL 2: Fetch Transcript ---
def ask_rag(video_id, question):
    try:
        # Fetch the transcript
        ytt_api = YouTubeTranscriptApi()
        transcript_list = ytt_api.fetch(video_id, languages=["en"])

        # FIX: Use chunk.text instead of chunk["text"]
        transcript = " ".join(chunk.text for chunk in transcript_list)

    except TranscriptsDisabled:
        return "No captions are available for this video."
    except Exception as e:
        return f"An error occurred: {e}"

    splitter=RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=200)
    chunks=splitter.create_documents([transcript])

    from langchain_huggingface import HuggingFaceEmbeddings
    from langchain_community.vectorstores import FAISS

    # Initialize the free Hugging Face embedding model (it will download the first time you run it)
    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

    # Create your FAISS vector store
    vector_store = FAISS.from_documents(chunks, embeddings)

    retriever=vector_store.as_retriever(search_type="similarity",search_kwargs={"k":4})

    import os
    from langchain_groq import ChatGroq
    from langchain_core.prompts import ChatPromptTemplate
    # FIX: Import from langchain_classic instead of langchain
    from langchain_classic.chains.combine_documents import create_stuff_documents_chain
    from langchain_classic.chains import create_retrieval_chain
    llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0.2)

    # 1. Define the system prompt string
    system_prompt = (
        "You are a helpful assistant. Use the following pieces of retrieved video "
        "transcript to answer the question. If you don't know the answer, just say "
        "that you don't know. \n\n"
        "Context: {context}"
    )

    # 2. Create the ChatPromptTemplate
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
    ])

    # 3. Create the document combination chain & final retrieval chain
    combine_docs_chain = create_stuff_documents_chain(llm, prompt)
    rag_chain = create_retrieval_chain(retriever, combine_docs_chain)

    from langchain_core.runnables import RunnableParallel,RunnablePassthrough,RunnableLambda
    from langchain_core.output_parsers import StrOutputParser

    def format_docs(retrieved_docs):
        context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
        return context_text

    parallel_chain = RunnableParallel({
        'context': retriever | RunnableLambda(format_docs),#when the context arrives it goes to retriever and it goes to format_docs
        'input': RunnablePassthrough()
    })

    parser=StrOutputParser()
    main_chain=parallel_chain | prompt | llm |parser
    answer = main_chain.invoke(question)

    return answer

